// Code generated by script in generate/ DO NOT EDIT.

package mime

var trueVal = true
var falseVal = false

// source https://github.com/jshttp/mime-db
var mimeTypes = map[string]*Spec{
	"application/andrew-inset": &Spec{
		Source:     "iana",
		Extensions: []string{"ez"},
	},
	"application/applixware": &Spec{
		Source:     "apache",
		Extensions: []string{"aw"},
	},
	"application/atom+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"atom"},
	},
	"application/atomcat+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"atomcat"},
	},
	"application/atomdeleted+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"atomdeleted"},
	},
	"application/atomsvc+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"atomsvc"},
	},
	"application/atsc-dwd+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"dwd"},
	},
	"application/atsc-held+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"held"},
	},
	"application/atsc-rsat+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"rsat"},
	},
	"application/bdoc": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"bdoc"},
	},
	"application/calendar+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xcs"},
	},
	"application/ccxml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"ccxml"},
	},
	"application/cdfx+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"cdfx"},
	},
	"application/cdmi-capability": &Spec{
		Source:     "iana",
		Extensions: []string{"cdmia"},
	},
	"application/cdmi-container": &Spec{
		Source:     "iana",
		Extensions: []string{"cdmic"},
	},
	"application/cdmi-domain": &Spec{
		Source:     "iana",
		Extensions: []string{"cdmid"},
	},
	"application/cdmi-object": &Spec{
		Source:     "iana",
		Extensions: []string{"cdmio"},
	},
	"application/cdmi-queue": &Spec{
		Source:     "iana",
		Extensions: []string{"cdmiq"},
	},
	"application/cu-seeme": &Spec{
		Source:     "apache",
		Extensions: []string{"cu"},
	},
	"application/dash+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"mpd"},
	},
	"application/davmount+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"davmount"},
	},
	"application/docbook+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"dbk"},
	},
	"application/dssc+der": &Spec{
		Source:     "iana",
		Extensions: []string{"dssc"},
	},
	"application/dssc+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xdssc"},
	},
	"application/ecmascript": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"es", "ecma"},
	},
	"application/emma+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"emma"},
	},
	"application/emotionml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"emotionml"},
	},
	"application/epub+zip": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"epub"},
	},
	"application/exi": &Spec{
		Source:     "iana",
		Extensions: []string{"exi"},
	},
	"application/express": &Spec{
		Source:     "iana",
		Extensions: []string{"exp"},
	},
	"application/fdt+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"fdt"},
	},
	"application/font-tdpfr": &Spec{
		Source:     "iana",
		Extensions: []string{"pfr"},
	},
	"application/geo+json": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"geojson"},
	},
	"application/gml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"gml"},
	},
	"application/gpx+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"gpx"},
	},
	"application/gxf": &Spec{
		Source:     "apache",
		Extensions: []string{"gxf"},
	},
	"application/gzip": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"gz"},
	},
	"application/hjson": &Spec{
		Extensions: []string{"hjson"},
	},
	"application/hyperstudio": &Spec{
		Source:     "iana",
		Extensions: []string{"stk"},
	},
	"application/inkml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"ink", "inkml"},
	},
	"application/ipfix": &Spec{
		Source:     "iana",
		Extensions: []string{"ipfix"},
	},
	"application/its+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"its"},
	},
	"application/java-archive": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"jar", "war", "ear"},
	},
	"application/java-serialized-object": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"ser"},
	},
	"application/java-vm": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"class"},
	},
	"application/javascript": &Spec{
		Source:       "iana",
		CharEncoding: "UTF-8",
		Compressible: &trueVal,
		Extensions:   []string{"js", "mjs"},
	},
	"application/json": &Spec{
		Source:       "iana",
		CharEncoding: "UTF-8",
		Compressible: &trueVal,
		Extensions:   []string{"json", "map"},
	},
	"application/json5": &Spec{
		Extensions: []string{"json5"},
	},
	"application/jsonml+json": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"jsonml"},
	},
	"application/ld+json": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"jsonld"},
	},
	"application/lgr+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"lgr"},
	},
	"application/lost+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"lostxml"},
	},
	"application/mac-binhex40": &Spec{
		Source:     "iana",
		Extensions: []string{"hqx"},
	},
	"application/mac-compactpro": &Spec{
		Source:     "apache",
		Extensions: []string{"cpt"},
	},
	"application/mads+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"mads"},
	},
	"application/manifest+json": &Spec{
		Source:       "iana",
		CharEncoding: "UTF-8",
		Compressible: &trueVal,
		Extensions:   []string{"webmanifest"},
	},
	"application/marc": &Spec{
		Source:     "iana",
		Extensions: []string{"mrc"},
	},
	"application/marcxml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"mrcx"},
	},
	"application/mathematica": &Spec{
		Source:     "iana",
		Extensions: []string{"ma", "nb", "mb"},
	},
	"application/mathml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"mathml"},
	},
	"application/mbox": &Spec{
		Source:     "iana",
		Extensions: []string{"mbox"},
	},
	"application/mediaservercontrol+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"mscml"},
	},
	"application/metalink+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"metalink"},
	},
	"application/metalink4+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"meta4"},
	},
	"application/mets+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"mets"},
	},
	"application/mmt-aei+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"maei"},
	},
	"application/mmt-usd+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"musd"},
	},
	"application/mods+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"mods"},
	},
	"application/mp21": &Spec{
		Source:     "iana",
		Extensions: []string{"m21", "mp21"},
	},
	"application/mp4": &Spec{
		Source:     "iana",
		Extensions: []string{"mp4s", "m4p"},
	},
	"application/msword": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"doc", "dot"},
	},
	"application/mxf": &Spec{
		Source:     "iana",
		Extensions: []string{"mxf"},
	},
	"application/n-quads": &Spec{
		Source:     "iana",
		Extensions: []string{"nq"},
	},
	"application/n-triples": &Spec{
		Source:     "iana",
		Extensions: []string{"nt"},
	},
	"application/node": &Spec{
		Source:     "iana",
		Extensions: []string{"cjs"},
	},
	"application/octet-stream": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"bin", "dms", "lrf", "mar", "so", "dist", "distz", "pkg", "bpk", "dump", "elc", "deploy", "exe", "dll", "deb", "dmg", "iso", "img", "msi", "msp", "msm", "buffer"},
	},
	"application/oda": &Spec{
		Source:     "iana",
		Extensions: []string{"oda"},
	},
	"application/oebps-package+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"opf"},
	},
	"application/ogg": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"ogx"},
	},
	"application/omdoc+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"omdoc"},
	},
	"application/onenote": &Spec{
		Source:     "apache",
		Extensions: []string{"onetoc", "onetoc2", "onetmp", "onepkg"},
	},
	"application/oxps": &Spec{
		Source:     "iana",
		Extensions: []string{"oxps"},
	},
	"application/p2p-overlay+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"relo"},
	},
	"application/patch-ops-error+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xer"},
	},
	"application/pdf": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"pdf"},
	},
	"application/pgp-encrypted": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"pgp"},
	},
	"application/pgp-signature": &Spec{
		Source:     "iana",
		Extensions: []string{"asc", "sig"},
	},
	"application/pics-rules": &Spec{
		Source:     "apache",
		Extensions: []string{"prf"},
	},
	"application/pkcs10": &Spec{
		Source:     "iana",
		Extensions: []string{"p10"},
	},
	"application/pkcs7-mime": &Spec{
		Source:     "iana",
		Extensions: []string{"p7m", "p7c"},
	},
	"application/pkcs7-signature": &Spec{
		Source:     "iana",
		Extensions: []string{"p7s"},
	},
	"application/pkcs8": &Spec{
		Source:     "iana",
		Extensions: []string{"p8"},
	},
	"application/pkix-attr-cert": &Spec{
		Source:     "iana",
		Extensions: []string{"ac"},
	},
	"application/pkix-cert": &Spec{
		Source:     "iana",
		Extensions: []string{"cer"},
	},
	"application/pkix-crl": &Spec{
		Source:     "iana",
		Extensions: []string{"crl"},
	},
	"application/pkix-pkipath": &Spec{
		Source:     "iana",
		Extensions: []string{"pkipath"},
	},
	"application/pkixcmp": &Spec{
		Source:     "iana",
		Extensions: []string{"pki"},
	},
	"application/pls+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"pls"},
	},
	"application/postscript": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"ai", "eps", "ps"},
	},
	"application/provenance+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"provx"},
	},
	"application/prs.cww": &Spec{
		Source:     "iana",
		Extensions: []string{"cww"},
	},
	"application/pskc+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"pskcxml"},
	},
	"application/raml+yaml": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"raml"},
	},
	"application/rdf+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"rdf", "owl"},
	},
	"application/reginfo+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"rif"},
	},
	"application/relax-ng-compact-syntax": &Spec{
		Source:     "iana",
		Extensions: []string{"rnc"},
	},
	"application/resource-lists+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"rl"},
	},
	"application/resource-lists-diff+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"rld"},
	},
	"application/rls-services+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"rs"},
	},
	"application/route-apd+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"rapd"},
	},
	"application/route-s-tsid+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"sls"},
	},
	"application/route-usd+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"rusd"},
	},
	"application/rpki-ghostbusters": &Spec{
		Source:     "iana",
		Extensions: []string{"gbr"},
	},
	"application/rpki-manifest": &Spec{
		Source:     "iana",
		Extensions: []string{"mft"},
	},
	"application/rpki-roa": &Spec{
		Source:     "iana",
		Extensions: []string{"roa"},
	},
	"application/rsd+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"rsd"},
	},
	"application/rss+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"rss"},
	},
	"application/rtf": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"rtf"},
	},
	"application/sbml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"sbml"},
	},
	"application/scvp-cv-request": &Spec{
		Source:     "iana",
		Extensions: []string{"scq"},
	},
	"application/scvp-cv-response": &Spec{
		Source:     "iana",
		Extensions: []string{"scs"},
	},
	"application/scvp-vp-request": &Spec{
		Source:     "iana",
		Extensions: []string{"spq"},
	},
	"application/scvp-vp-response": &Spec{
		Source:     "iana",
		Extensions: []string{"spp"},
	},
	"application/sdp": &Spec{
		Source:     "iana",
		Extensions: []string{"sdp"},
	},
	"application/senml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"senmlx"},
	},
	"application/sensml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"sensmlx"},
	},
	"application/set-payment-initiation": &Spec{
		Source:     "iana",
		Extensions: []string{"setpay"},
	},
	"application/set-registration-initiation": &Spec{
		Source:     "iana",
		Extensions: []string{"setreg"},
	},
	"application/shf+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"shf"},
	},
	"application/sieve": &Spec{
		Source:     "iana",
		Extensions: []string{"siv", "sieve"},
	},
	"application/smil+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"smi", "smil"},
	},
	"application/sparql-query": &Spec{
		Source:     "iana",
		Extensions: []string{"rq"},
	},
	"application/sparql-results+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"srx"},
	},
	"application/srgs": &Spec{
		Source:     "iana",
		Extensions: []string{"gram"},
	},
	"application/srgs+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"grxml"},
	},
	"application/sru+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"sru"},
	},
	"application/ssdl+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"ssdl"},
	},
	"application/ssml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"ssml"},
	},
	"application/swid+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"swidtag"},
	},
	"application/tei+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"tei", "teicorpus"},
	},
	"application/thraud+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"tfi"},
	},
	"application/timestamped-data": &Spec{
		Source:     "iana",
		Extensions: []string{"tsd"},
	},
	"application/toml": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"toml"},
	},
	"application/trig": &Spec{
		Source:     "iana",
		Extensions: []string{"trig"},
	},
	"application/ttml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"ttml"},
	},
	"application/ubjson": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"ubj"},
	},
	"application/urc-ressheet+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"rsheet"},
	},
	"application/urc-targetdesc+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"td"},
	},
	"application/vnd.1000minds.decision-model+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"1km"},
	},
	"application/vnd.3gpp.pic-bw-large": &Spec{
		Source:     "iana",
		Extensions: []string{"plb"},
	},
	"application/vnd.3gpp.pic-bw-small": &Spec{
		Source:     "iana",
		Extensions: []string{"psb"},
	},
	"application/vnd.3gpp.pic-bw-var": &Spec{
		Source:     "iana",
		Extensions: []string{"pvb"},
	},
	"application/vnd.3gpp2.tcap": &Spec{
		Source:     "iana",
		Extensions: []string{"tcap"},
	},
	"application/vnd.3m.post-it-notes": &Spec{
		Source:     "iana",
		Extensions: []string{"pwn"},
	},
	"application/vnd.accpac.simply.aso": &Spec{
		Source:     "iana",
		Extensions: []string{"aso"},
	},
	"application/vnd.accpac.simply.imp": &Spec{
		Source:     "iana",
		Extensions: []string{"imp"},
	},
	"application/vnd.acucobol": &Spec{
		Source:     "iana",
		Extensions: []string{"acu"},
	},
	"application/vnd.acucorp": &Spec{
		Source:     "iana",
		Extensions: []string{"atc", "acutc"},
	},
	"application/vnd.adobe.air-application-installer-package+zip": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"air"},
	},
	"application/vnd.adobe.formscentral.fcdt": &Spec{
		Source:     "iana",
		Extensions: []string{"fcdt"},
	},
	"application/vnd.adobe.fxp": &Spec{
		Source:     "iana",
		Extensions: []string{"fxp", "fxpl"},
	},
	"application/vnd.adobe.xdp+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xdp"},
	},
	"application/vnd.adobe.xfdf": &Spec{
		Source:     "iana",
		Extensions: []string{"xfdf"},
	},
	"application/vnd.age": &Spec{
		Source:     "iana",
		Extensions: []string{"age"},
	},
	"application/vnd.ahead.space": &Spec{
		Source:     "iana",
		Extensions: []string{"ahead"},
	},
	"application/vnd.airzip.filesecure.azf": &Spec{
		Source:     "iana",
		Extensions: []string{"azf"},
	},
	"application/vnd.airzip.filesecure.azs": &Spec{
		Source:     "iana",
		Extensions: []string{"azs"},
	},
	"application/vnd.amazon.ebook": &Spec{
		Source:     "apache",
		Extensions: []string{"azw"},
	},
	"application/vnd.americandynamics.acc": &Spec{
		Source:     "iana",
		Extensions: []string{"acc"},
	},
	"application/vnd.amiga.ami": &Spec{
		Source:     "iana",
		Extensions: []string{"ami"},
	},
	"application/vnd.android.package-archive": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"apk"},
	},
	"application/vnd.anser-web-certificate-issue-initiation": &Spec{
		Source:     "iana",
		Extensions: []string{"cii"},
	},
	"application/vnd.anser-web-funds-transfer-initiation": &Spec{
		Source:     "apache",
		Extensions: []string{"fti"},
	},
	"application/vnd.antix.game-component": &Spec{
		Source:     "iana",
		Extensions: []string{"atx"},
	},
	"application/vnd.apple.installer+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"mpkg"},
	},
	"application/vnd.apple.keynote": &Spec{
		Source:     "iana",
		Extensions: []string{"key"},
	},
	"application/vnd.apple.mpegurl": &Spec{
		Source:     "iana",
		Extensions: []string{"m3u8"},
	},
	"application/vnd.apple.numbers": &Spec{
		Source:     "iana",
		Extensions: []string{"numbers"},
	},
	"application/vnd.apple.pages": &Spec{
		Source:     "iana",
		Extensions: []string{"pages"},
	},
	"application/vnd.apple.pkpass": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"pkpass"},
	},
	"application/vnd.aristanetworks.swi": &Spec{
		Source:     "iana",
		Extensions: []string{"swi"},
	},
	"application/vnd.astraea-software.iota": &Spec{
		Source:     "iana",
		Extensions: []string{"iota"},
	},
	"application/vnd.audiograph": &Spec{
		Source:     "iana",
		Extensions: []string{"aep"},
	},
	"application/vnd.balsamiq.bmml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"bmml"},
	},
	"application/vnd.blueice.multipass": &Spec{
		Source:     "iana",
		Extensions: []string{"mpm"},
	},
	"application/vnd.bmi": &Spec{
		Source:     "iana",
		Extensions: []string{"bmi"},
	},
	"application/vnd.businessobjects": &Spec{
		Source:     "iana",
		Extensions: []string{"rep"},
	},
	"application/vnd.chemdraw+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"cdxml"},
	},
	"application/vnd.chipnuts.karaoke-mmd": &Spec{
		Source:     "iana",
		Extensions: []string{"mmd"},
	},
	"application/vnd.cinderella": &Spec{
		Source:     "iana",
		Extensions: []string{"cdy"},
	},
	"application/vnd.citationstyles.style+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"csl"},
	},
	"application/vnd.claymore": &Spec{
		Source:     "iana",
		Extensions: []string{"cla"},
	},
	"application/vnd.cloanto.rp9": &Spec{
		Source:     "iana",
		Extensions: []string{"rp9"},
	},
	"application/vnd.clonk.c4group": &Spec{
		Source:     "iana",
		Extensions: []string{"c4g", "c4d", "c4f", "c4p", "c4u"},
	},
	"application/vnd.cluetrust.cartomobile-config": &Spec{
		Source:     "iana",
		Extensions: []string{"c11amc"},
	},
	"application/vnd.cluetrust.cartomobile-config-pkg": &Spec{
		Source:     "iana",
		Extensions: []string{"c11amz"},
	},
	"application/vnd.commonspace": &Spec{
		Source:     "iana",
		Extensions: []string{"csp"},
	},
	"application/vnd.contact.cmsg": &Spec{
		Source:     "iana",
		Extensions: []string{"cdbcmsg"},
	},
	"application/vnd.cosmocaller": &Spec{
		Source:     "iana",
		Extensions: []string{"cmc"},
	},
	"application/vnd.crick.clicker": &Spec{
		Source:     "iana",
		Extensions: []string{"clkx"},
	},
	"application/vnd.crick.clicker.keyboard": &Spec{
		Source:     "iana",
		Extensions: []string{"clkk"},
	},
	"application/vnd.crick.clicker.palette": &Spec{
		Source:     "iana",
		Extensions: []string{"clkp"},
	},
	"application/vnd.crick.clicker.template": &Spec{
		Source:     "iana",
		Extensions: []string{"clkt"},
	},
	"application/vnd.crick.clicker.wordbank": &Spec{
		Source:     "iana",
		Extensions: []string{"clkw"},
	},
	"application/vnd.criticaltools.wbs+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"wbs"},
	},
	"application/vnd.ctc-posml": &Spec{
		Source:     "iana",
		Extensions: []string{"pml"},
	},
	"application/vnd.cups-ppd": &Spec{
		Source:     "iana",
		Extensions: []string{"ppd"},
	},
	"application/vnd.curl.car": &Spec{
		Source:     "apache",
		Extensions: []string{"car"},
	},
	"application/vnd.curl.pcurl": &Spec{
		Source:     "apache",
		Extensions: []string{"pcurl"},
	},
	"application/vnd.dart": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"dart"},
	},
	"application/vnd.data-vision.rdz": &Spec{
		Source:     "iana",
		Extensions: []string{"rdz"},
	},
	"application/vnd.dbf": &Spec{
		Source:     "iana",
		Extensions: []string{"dbf"},
	},
	"application/vnd.dece.data": &Spec{
		Source:     "iana",
		Extensions: []string{"uvf", "uvvf", "uvd", "uvvd"},
	},
	"application/vnd.dece.ttml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"uvt", "uvvt"},
	},
	"application/vnd.dece.unspecified": &Spec{
		Source:     "iana",
		Extensions: []string{"uvx", "uvvx"},
	},
	"application/vnd.dece.zip": &Spec{
		Source:     "iana",
		Extensions: []string{"uvz", "uvvz"},
	},
	"application/vnd.denovo.fcselayout-link": &Spec{
		Source:     "iana",
		Extensions: []string{"fe_launch"},
	},
	"application/vnd.dna": &Spec{
		Source:     "iana",
		Extensions: []string{"dna"},
	},
	"application/vnd.dolby.mlp": &Spec{
		Source:     "apache",
		Extensions: []string{"mlp"},
	},
	"application/vnd.dpgraph": &Spec{
		Source:     "iana",
		Extensions: []string{"dpg"},
	},
	"application/vnd.dreamfactory": &Spec{
		Source:     "iana",
		Extensions: []string{"dfac"},
	},
	"application/vnd.ds-keypoint": &Spec{
		Source:     "apache",
		Extensions: []string{"kpxx"},
	},
	"application/vnd.dvb.ait": &Spec{
		Source:     "iana",
		Extensions: []string{"ait"},
	},
	"application/vnd.dvb.service": &Spec{
		Source:     "iana",
		Extensions: []string{"svc"},
	},
	"application/vnd.dynageo": &Spec{
		Source:     "iana",
		Extensions: []string{"geo"},
	},
	"application/vnd.ecowin.chart": &Spec{
		Source:     "iana",
		Extensions: []string{"mag"},
	},
	"application/vnd.enliven": &Spec{
		Source:     "iana",
		Extensions: []string{"nml"},
	},
	"application/vnd.epson.esf": &Spec{
		Source:     "iana",
		Extensions: []string{"esf"},
	},
	"application/vnd.epson.msf": &Spec{
		Source:     "iana",
		Extensions: []string{"msf"},
	},
	"application/vnd.epson.quickanime": &Spec{
		Source:     "iana",
		Extensions: []string{"qam"},
	},
	"application/vnd.epson.salt": &Spec{
		Source:     "iana",
		Extensions: []string{"slt"},
	},
	"application/vnd.epson.ssf": &Spec{
		Source:     "iana",
		Extensions: []string{"ssf"},
	},
	"application/vnd.eszigno3+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"es3", "et3"},
	},
	"application/vnd.ezpix-album": &Spec{
		Source:     "iana",
		Extensions: []string{"ez2"},
	},
	"application/vnd.ezpix-package": &Spec{
		Source:     "iana",
		Extensions: []string{"ez3"},
	},
	"application/vnd.fdf": &Spec{
		Source:     "iana",
		Extensions: []string{"fdf"},
	},
	"application/vnd.fdsn.mseed": &Spec{
		Source:     "iana",
		Extensions: []string{"mseed"},
	},
	"application/vnd.fdsn.seed": &Spec{
		Source:     "iana",
		Extensions: []string{"seed", "dataless"},
	},
	"application/vnd.flographit": &Spec{
		Source:     "iana",
		Extensions: []string{"gph"},
	},
	"application/vnd.fluxtime.clip": &Spec{
		Source:     "iana",
		Extensions: []string{"ftc"},
	},
	"application/vnd.framemaker": &Spec{
		Source:     "iana",
		Extensions: []string{"fm", "frame", "maker", "book"},
	},
	"application/vnd.frogans.fnc": &Spec{
		Source:     "iana",
		Extensions: []string{"fnc"},
	},
	"application/vnd.frogans.ltf": &Spec{
		Source:     "iana",
		Extensions: []string{"ltf"},
	},
	"application/vnd.fsc.weblaunch": &Spec{
		Source:     "iana",
		Extensions: []string{"fsc"},
	},
	"application/vnd.fujitsu.oasys": &Spec{
		Source:     "iana",
		Extensions: []string{"oas"},
	},
	"application/vnd.fujitsu.oasys2": &Spec{
		Source:     "iana",
		Extensions: []string{"oa2"},
	},
	"application/vnd.fujitsu.oasys3": &Spec{
		Source:     "iana",
		Extensions: []string{"oa3"},
	},
	"application/vnd.fujitsu.oasysgp": &Spec{
		Source:     "iana",
		Extensions: []string{"fg5"},
	},
	"application/vnd.fujitsu.oasysprs": &Spec{
		Source:     "iana",
		Extensions: []string{"bh2"},
	},
	"application/vnd.fujixerox.ddd": &Spec{
		Source:     "iana",
		Extensions: []string{"ddd"},
	},
	"application/vnd.fujixerox.docuworks": &Spec{
		Source:     "iana",
		Extensions: []string{"xdw"},
	},
	"application/vnd.fujixerox.docuworks.binder": &Spec{
		Source:     "iana",
		Extensions: []string{"xbd"},
	},
	"application/vnd.fuzzysheet": &Spec{
		Source:     "iana",
		Extensions: []string{"fzs"},
	},
	"application/vnd.genomatix.tuxedo": &Spec{
		Source:     "iana",
		Extensions: []string{"txd"},
	},
	"application/vnd.geogebra.file": &Spec{
		Source:     "iana",
		Extensions: []string{"ggb"},
	},
	"application/vnd.geogebra.tool": &Spec{
		Source:     "iana",
		Extensions: []string{"ggt"},
	},
	"application/vnd.geometry-explorer": &Spec{
		Source:     "iana",
		Extensions: []string{"gex", "gre"},
	},
	"application/vnd.geonext": &Spec{
		Source:     "iana",
		Extensions: []string{"gxt"},
	},
	"application/vnd.geoplan": &Spec{
		Source:     "iana",
		Extensions: []string{"g2w"},
	},
	"application/vnd.geospace": &Spec{
		Source:     "iana",
		Extensions: []string{"g3w"},
	},
	"application/vnd.gmx": &Spec{
		Source:     "iana",
		Extensions: []string{"gmx"},
	},
	"application/vnd.google-apps.document": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"gdoc"},
	},
	"application/vnd.google-apps.presentation": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"gslides"},
	},
	"application/vnd.google-apps.spreadsheet": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"gsheet"},
	},
	"application/vnd.google-earth.kml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"kml"},
	},
	"application/vnd.google-earth.kmz": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"kmz"},
	},
	"application/vnd.grafeq": &Spec{
		Source:     "iana",
		Extensions: []string{"gqf", "gqs"},
	},
	"application/vnd.groove-account": &Spec{
		Source:     "iana",
		Extensions: []string{"gac"},
	},
	"application/vnd.groove-help": &Spec{
		Source:     "iana",
		Extensions: []string{"ghf"},
	},
	"application/vnd.groove-identity-message": &Spec{
		Source:     "iana",
		Extensions: []string{"gim"},
	},
	"application/vnd.groove-injector": &Spec{
		Source:     "iana",
		Extensions: []string{"grv"},
	},
	"application/vnd.groove-tool-message": &Spec{
		Source:     "iana",
		Extensions: []string{"gtm"},
	},
	"application/vnd.groove-tool-template": &Spec{
		Source:     "iana",
		Extensions: []string{"tpl"},
	},
	"application/vnd.groove-vcard": &Spec{
		Source:     "iana",
		Extensions: []string{"vcg"},
	},
	"application/vnd.hal+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"hal"},
	},
	"application/vnd.handheld-entertainment+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"zmm"},
	},
	"application/vnd.hbci": &Spec{
		Source:     "iana",
		Extensions: []string{"hbci"},
	},
	"application/vnd.hhe.lesson-player": &Spec{
		Source:     "iana",
		Extensions: []string{"les"},
	},
	"application/vnd.hp-hpgl": &Spec{
		Source:     "iana",
		Extensions: []string{"hpgl"},
	},
	"application/vnd.hp-hpid": &Spec{
		Source:     "iana",
		Extensions: []string{"hpid"},
	},
	"application/vnd.hp-hps": &Spec{
		Source:     "iana",
		Extensions: []string{"hps"},
	},
	"application/vnd.hp-jlyt": &Spec{
		Source:     "iana",
		Extensions: []string{"jlt"},
	},
	"application/vnd.hp-pcl": &Spec{
		Source:     "iana",
		Extensions: []string{"pcl"},
	},
	"application/vnd.hp-pclxl": &Spec{
		Source:     "iana",
		Extensions: []string{"pclxl"},
	},
	"application/vnd.hydrostatix.sof-data": &Spec{
		Source:     "iana",
		Extensions: []string{"sfd-hdstx"},
	},
	"application/vnd.ibm.minipay": &Spec{
		Source:     "iana",
		Extensions: []string{"mpy"},
	},
	"application/vnd.ibm.modcap": &Spec{
		Source:     "iana",
		Extensions: []string{"afp", "listafp", "list3820"},
	},
	"application/vnd.ibm.rights-management": &Spec{
		Source:     "iana",
		Extensions: []string{"irm"},
	},
	"application/vnd.ibm.secure-container": &Spec{
		Source:     "iana",
		Extensions: []string{"sc"},
	},
	"application/vnd.iccprofile": &Spec{
		Source:     "iana",
		Extensions: []string{"icc", "icm"},
	},
	"application/vnd.igloader": &Spec{
		Source:     "iana",
		Extensions: []string{"igl"},
	},
	"application/vnd.immervision-ivp": &Spec{
		Source:     "iana",
		Extensions: []string{"ivp"},
	},
	"application/vnd.immervision-ivu": &Spec{
		Source:     "iana",
		Extensions: []string{"ivu"},
	},
	"application/vnd.insors.igm": &Spec{
		Source:     "iana",
		Extensions: []string{"igm"},
	},
	"application/vnd.intercon.formnet": &Spec{
		Source:     "iana",
		Extensions: []string{"xpw", "xpx"},
	},
	"application/vnd.intergeo": &Spec{
		Source:     "iana",
		Extensions: []string{"i2g"},
	},
	"application/vnd.intu.qbo": &Spec{
		Source:     "iana",
		Extensions: []string{"qbo"},
	},
	"application/vnd.intu.qfx": &Spec{
		Source:     "iana",
		Extensions: []string{"qfx"},
	},
	"application/vnd.ipunplugged.rcprofile": &Spec{
		Source:     "iana",
		Extensions: []string{"rcprofile"},
	},
	"application/vnd.irepository.package+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"irp"},
	},
	"application/vnd.is-xpr": &Spec{
		Source:     "iana",
		Extensions: []string{"xpr"},
	},
	"application/vnd.isac.fcs": &Spec{
		Source:     "iana",
		Extensions: []string{"fcs"},
	},
	"application/vnd.jam": &Spec{
		Source:     "iana",
		Extensions: []string{"jam"},
	},
	"application/vnd.jcp.javame.midlet-rms": &Spec{
		Source:     "iana",
		Extensions: []string{"rms"},
	},
	"application/vnd.jisp": &Spec{
		Source:     "iana",
		Extensions: []string{"jisp"},
	},
	"application/vnd.joost.joda-archive": &Spec{
		Source:     "iana",
		Extensions: []string{"joda"},
	},
	"application/vnd.kahootz": &Spec{
		Source:     "iana",
		Extensions: []string{"ktz", "ktr"},
	},
	"application/vnd.kde.karbon": &Spec{
		Source:     "iana",
		Extensions: []string{"karbon"},
	},
	"application/vnd.kde.kchart": &Spec{
		Source:     "iana",
		Extensions: []string{"chrt"},
	},
	"application/vnd.kde.kformula": &Spec{
		Source:     "iana",
		Extensions: []string{"kfo"},
	},
	"application/vnd.kde.kivio": &Spec{
		Source:     "iana",
		Extensions: []string{"flw"},
	},
	"application/vnd.kde.kontour": &Spec{
		Source:     "iana",
		Extensions: []string{"kon"},
	},
	"application/vnd.kde.kpresenter": &Spec{
		Source:     "iana",
		Extensions: []string{"kpr", "kpt"},
	},
	"application/vnd.kde.kspread": &Spec{
		Source:     "iana",
		Extensions: []string{"ksp"},
	},
	"application/vnd.kde.kword": &Spec{
		Source:     "iana",
		Extensions: []string{"kwd", "kwt"},
	},
	"application/vnd.kenameaapp": &Spec{
		Source:     "iana",
		Extensions: []string{"htke"},
	},
	"application/vnd.kidspiration": &Spec{
		Source:     "iana",
		Extensions: []string{"kia"},
	},
	"application/vnd.kinar": &Spec{
		Source:     "iana",
		Extensions: []string{"kne", "knp"},
	},
	"application/vnd.koan": &Spec{
		Source:     "iana",
		Extensions: []string{"skp", "skd", "skt", "skm"},
	},
	"application/vnd.kodak-descriptor": &Spec{
		Source:     "iana",
		Extensions: []string{"sse"},
	},
	"application/vnd.las.las+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"lasxml"},
	},
	"application/vnd.llamagraphics.life-balance.desktop": &Spec{
		Source:     "iana",
		Extensions: []string{"lbd"},
	},
	"application/vnd.llamagraphics.life-balance.exchange+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"lbe"},
	},
	"application/vnd.lotus-1-2-3": &Spec{
		Source:     "iana",
		Extensions: []string{"123"},
	},
	"application/vnd.lotus-approach": &Spec{
		Source:     "iana",
		Extensions: []string{"apr"},
	},
	"application/vnd.lotus-freelance": &Spec{
		Source:     "iana",
		Extensions: []string{"pre"},
	},
	"application/vnd.lotus-notes": &Spec{
		Source:     "iana",
		Extensions: []string{"nsf"},
	},
	"application/vnd.lotus-organizer": &Spec{
		Source:     "iana",
		Extensions: []string{"org"},
	},
	"application/vnd.lotus-screencam": &Spec{
		Source:     "iana",
		Extensions: []string{"scm"},
	},
	"application/vnd.lotus-wordpro": &Spec{
		Source:     "iana",
		Extensions: []string{"lwp"},
	},
	"application/vnd.macports.portpkg": &Spec{
		Source:     "iana",
		Extensions: []string{"portpkg"},
	},
	"application/vnd.mapbox-vector-tile": &Spec{
		Source:     "iana",
		Extensions: []string{"mvt"},
	},
	"application/vnd.mcd": &Spec{
		Source:     "iana",
		Extensions: []string{"mcd"},
	},
	"application/vnd.medcalcdata": &Spec{
		Source:     "iana",
		Extensions: []string{"mc1"},
	},
	"application/vnd.mediastation.cdkey": &Spec{
		Source:     "iana",
		Extensions: []string{"cdkey"},
	},
	"application/vnd.mfer": &Spec{
		Source:     "iana",
		Extensions: []string{"mwf"},
	},
	"application/vnd.mfmp": &Spec{
		Source:     "iana",
		Extensions: []string{"mfm"},
	},
	"application/vnd.micrografx.flo": &Spec{
		Source:     "iana",
		Extensions: []string{"flo"},
	},
	"application/vnd.micrografx.igx": &Spec{
		Source:     "iana",
		Extensions: []string{"igx"},
	},
	"application/vnd.mif": &Spec{
		Source:     "iana",
		Extensions: []string{"mif"},
	},
	"application/vnd.mobius.daf": &Spec{
		Source:     "iana",
		Extensions: []string{"daf"},
	},
	"application/vnd.mobius.dis": &Spec{
		Source:     "iana",
		Extensions: []string{"dis"},
	},
	"application/vnd.mobius.mbk": &Spec{
		Source:     "iana",
		Extensions: []string{"mbk"},
	},
	"application/vnd.mobius.mqy": &Spec{
		Source:     "iana",
		Extensions: []string{"mqy"},
	},
	"application/vnd.mobius.msl": &Spec{
		Source:     "iana",
		Extensions: []string{"msl"},
	},
	"application/vnd.mobius.plc": &Spec{
		Source:     "iana",
		Extensions: []string{"plc"},
	},
	"application/vnd.mobius.txf": &Spec{
		Source:     "iana",
		Extensions: []string{"txf"},
	},
	"application/vnd.mophun.application": &Spec{
		Source:     "iana",
		Extensions: []string{"mpn"},
	},
	"application/vnd.mophun.certificate": &Spec{
		Source:     "iana",
		Extensions: []string{"mpc"},
	},
	"application/vnd.mozilla.xul+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xul"},
	},
	"application/vnd.ms-artgalry": &Spec{
		Source:     "iana",
		Extensions: []string{"cil"},
	},
	"application/vnd.ms-cab-compressed": &Spec{
		Source:     "iana",
		Extensions: []string{"cab"},
	},
	"application/vnd.ms-excel": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"xls", "xlm", "xla", "xlc", "xlt", "xlw"},
	},
	"application/vnd.ms-excel.addin.macroenabled.12": &Spec{
		Source:     "iana",
		Extensions: []string{"xlam"},
	},
	"application/vnd.ms-excel.sheet.binary.macroenabled.12": &Spec{
		Source:     "iana",
		Extensions: []string{"xlsb"},
	},
	"application/vnd.ms-excel.sheet.macroenabled.12": &Spec{
		Source:     "iana",
		Extensions: []string{"xlsm"},
	},
	"application/vnd.ms-excel.template.macroenabled.12": &Spec{
		Source:     "iana",
		Extensions: []string{"xltm"},
	},
	"application/vnd.ms-fontobject": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"eot"},
	},
	"application/vnd.ms-htmlhelp": &Spec{
		Source:     "iana",
		Extensions: []string{"chm"},
	},
	"application/vnd.ms-ims": &Spec{
		Source:     "iana",
		Extensions: []string{"ims"},
	},
	"application/vnd.ms-lrm": &Spec{
		Source:     "iana",
		Extensions: []string{"lrm"},
	},
	"application/vnd.ms-officetheme": &Spec{
		Source:     "iana",
		Extensions: []string{"thmx"},
	},
	"application/vnd.ms-outlook": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"msg"},
	},
	"application/vnd.ms-pki.seccat": &Spec{
		Source:     "apache",
		Extensions: []string{"cat"},
	},
	"application/vnd.ms-pki.stl": &Spec{
		Source:     "apache",
		Extensions: []string{"stl"},
	},
	"application/vnd.ms-powerpoint": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"ppt", "pps", "pot"},
	},
	"application/vnd.ms-powerpoint.addin.macroenabled.12": &Spec{
		Source:     "iana",
		Extensions: []string{"ppam"},
	},
	"application/vnd.ms-powerpoint.presentation.macroenabled.12": &Spec{
		Source:     "iana",
		Extensions: []string{"pptm"},
	},
	"application/vnd.ms-powerpoint.slide.macroenabled.12": &Spec{
		Source:     "iana",
		Extensions: []string{"sldm"},
	},
	"application/vnd.ms-powerpoint.slideshow.macroenabled.12": &Spec{
		Source:     "iana",
		Extensions: []string{"ppsm"},
	},
	"application/vnd.ms-powerpoint.template.macroenabled.12": &Spec{
		Source:     "iana",
		Extensions: []string{"potm"},
	},
	"application/vnd.ms-project": &Spec{
		Source:     "iana",
		Extensions: []string{"mpp", "mpt"},
	},
	"application/vnd.ms-word.document.macroenabled.12": &Spec{
		Source:     "iana",
		Extensions: []string{"docm"},
	},
	"application/vnd.ms-word.template.macroenabled.12": &Spec{
		Source:     "iana",
		Extensions: []string{"dotm"},
	},
	"application/vnd.ms-works": &Spec{
		Source:     "iana",
		Extensions: []string{"wps", "wks", "wcm", "wdb"},
	},
	"application/vnd.ms-wpl": &Spec{
		Source:     "iana",
		Extensions: []string{"wpl"},
	},
	"application/vnd.ms-xpsdocument": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"xps"},
	},
	"application/vnd.mseq": &Spec{
		Source:     "iana",
		Extensions: []string{"mseq"},
	},
	"application/vnd.musician": &Spec{
		Source:     "iana",
		Extensions: []string{"mus"},
	},
	"application/vnd.muvee.style": &Spec{
		Source:     "iana",
		Extensions: []string{"msty"},
	},
	"application/vnd.mynfc": &Spec{
		Source:     "iana",
		Extensions: []string{"taglet"},
	},
	"application/vnd.neurolanguage.nlu": &Spec{
		Source:     "iana",
		Extensions: []string{"nlu"},
	},
	"application/vnd.nitf": &Spec{
		Source:     "iana",
		Extensions: []string{"ntf", "nitf"},
	},
	"application/vnd.noblenet-directory": &Spec{
		Source:     "iana",
		Extensions: []string{"nnd"},
	},
	"application/vnd.noblenet-sealer": &Spec{
		Source:     "iana",
		Extensions: []string{"nns"},
	},
	"application/vnd.noblenet-web": &Spec{
		Source:     "iana",
		Extensions: []string{"nnw"},
	},
	"application/vnd.nokia.n-gage.ac+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"ac"},
	},
	"application/vnd.nokia.n-gage.data": &Spec{
		Source:     "iana",
		Extensions: []string{"ngdat"},
	},
	"application/vnd.nokia.n-gage.symbian.install": &Spec{
		Source:     "iana",
		Extensions: []string{"n-gage"},
	},
	"application/vnd.nokia.radio-preset": &Spec{
		Source:     "iana",
		Extensions: []string{"rpst"},
	},
	"application/vnd.nokia.radio-presets": &Spec{
		Source:     "iana",
		Extensions: []string{"rpss"},
	},
	"application/vnd.novadigm.edm": &Spec{
		Source:     "iana",
		Extensions: []string{"edm"},
	},
	"application/vnd.novadigm.edx": &Spec{
		Source:     "iana",
		Extensions: []string{"edx"},
	},
	"application/vnd.novadigm.ext": &Spec{
		Source:     "iana",
		Extensions: []string{"ext"},
	},
	"application/vnd.oasis.opendocument.chart": &Spec{
		Source:     "iana",
		Extensions: []string{"odc"},
	},
	"application/vnd.oasis.opendocument.chart-template": &Spec{
		Source:     "iana",
		Extensions: []string{"otc"},
	},
	"application/vnd.oasis.opendocument.database": &Spec{
		Source:     "iana",
		Extensions: []string{"odb"},
	},
	"application/vnd.oasis.opendocument.formula": &Spec{
		Source:     "iana",
		Extensions: []string{"odf"},
	},
	"application/vnd.oasis.opendocument.formula-template": &Spec{
		Source:     "iana",
		Extensions: []string{"odft"},
	},
	"application/vnd.oasis.opendocument.graphics": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"odg"},
	},
	"application/vnd.oasis.opendocument.graphics-template": &Spec{
		Source:     "iana",
		Extensions: []string{"otg"},
	},
	"application/vnd.oasis.opendocument.image": &Spec{
		Source:     "iana",
		Extensions: []string{"odi"},
	},
	"application/vnd.oasis.opendocument.image-template": &Spec{
		Source:     "iana",
		Extensions: []string{"oti"},
	},
	"application/vnd.oasis.opendocument.presentation": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"odp"},
	},
	"application/vnd.oasis.opendocument.presentation-template": &Spec{
		Source:     "iana",
		Extensions: []string{"otp"},
	},
	"application/vnd.oasis.opendocument.spreadsheet": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"ods"},
	},
	"application/vnd.oasis.opendocument.spreadsheet-template": &Spec{
		Source:     "iana",
		Extensions: []string{"ots"},
	},
	"application/vnd.oasis.opendocument.text": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"odt"},
	},
	"application/vnd.oasis.opendocument.text-master": &Spec{
		Source:     "iana",
		Extensions: []string{"odm"},
	},
	"application/vnd.oasis.opendocument.text-template": &Spec{
		Source:     "iana",
		Extensions: []string{"ott"},
	},
	"application/vnd.oasis.opendocument.text-web": &Spec{
		Source:     "iana",
		Extensions: []string{"oth"},
	},
	"application/vnd.olpc-sugar": &Spec{
		Source:     "iana",
		Extensions: []string{"xo"},
	},
	"application/vnd.oma.dd2+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"dd2"},
	},
	"application/vnd.openblox.game+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"obgx"},
	},
	"application/vnd.openofficeorg.extension": &Spec{
		Source:     "apache",
		Extensions: []string{"oxt"},
	},
	"application/vnd.openstreetmap.data+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"osm"},
	},
	"application/vnd.openxmlformats-officedocument.presentationml.presentation": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"pptx"},
	},
	"application/vnd.openxmlformats-officedocument.presentationml.slide": &Spec{
		Source:     "iana",
		Extensions: []string{"sldx"},
	},
	"application/vnd.openxmlformats-officedocument.presentationml.slideshow": &Spec{
		Source:     "iana",
		Extensions: []string{"ppsx"},
	},
	"application/vnd.openxmlformats-officedocument.presentationml.template": &Spec{
		Source:     "iana",
		Extensions: []string{"potx"},
	},
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"xlsx"},
	},
	"application/vnd.openxmlformats-officedocument.spreadsheetml.template": &Spec{
		Source:     "iana",
		Extensions: []string{"xltx"},
	},
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"docx"},
	},
	"application/vnd.openxmlformats-officedocument.wordprocessingml.template": &Spec{
		Source:     "iana",
		Extensions: []string{"dotx"},
	},
	"application/vnd.osgeo.mapguide.package": &Spec{
		Source:     "iana",
		Extensions: []string{"mgp"},
	},
	"application/vnd.osgi.dp": &Spec{
		Source:     "iana",
		Extensions: []string{"dp"},
	},
	"application/vnd.osgi.subsystem": &Spec{
		Source:     "iana",
		Extensions: []string{"esa"},
	},
	"application/vnd.palm": &Spec{
		Source:     "iana",
		Extensions: []string{"pdb", "pqa", "oprc"},
	},
	"application/vnd.pawaafile": &Spec{
		Source:     "iana",
		Extensions: []string{"paw"},
	},
	"application/vnd.pg.format": &Spec{
		Source:     "iana",
		Extensions: []string{"str"},
	},
	"application/vnd.pg.osasli": &Spec{
		Source:     "iana",
		Extensions: []string{"ei6"},
	},
	"application/vnd.picsel": &Spec{
		Source:     "iana",
		Extensions: []string{"efif"},
	},
	"application/vnd.pmi.widget": &Spec{
		Source:     "iana",
		Extensions: []string{"wg"},
	},
	"application/vnd.pocketlearn": &Spec{
		Source:     "iana",
		Extensions: []string{"plf"},
	},
	"application/vnd.powerbuilder6": &Spec{
		Source:     "iana",
		Extensions: []string{"pbd"},
	},
	"application/vnd.previewsystems.box": &Spec{
		Source:     "iana",
		Extensions: []string{"box"},
	},
	"application/vnd.proteus.magazine": &Spec{
		Source:     "iana",
		Extensions: []string{"mgz"},
	},
	"application/vnd.publishare-delta-tree": &Spec{
		Source:     "iana",
		Extensions: []string{"qps"},
	},
	"application/vnd.pvi.ptid1": &Spec{
		Source:     "iana",
		Extensions: []string{"ptid"},
	},
	"application/vnd.quark.quarkxpress": &Spec{
		Source:     "iana",
		Extensions: []string{"qxd", "qxt", "qwd", "qwt", "qxl", "qxb"},
	},
	"application/vnd.rar": &Spec{
		Source:     "iana",
		Extensions: []string{"rar"},
	},
	"application/vnd.realvnc.bed": &Spec{
		Source:     "iana",
		Extensions: []string{"bed"},
	},
	"application/vnd.recordare.musicxml": &Spec{
		Source:     "iana",
		Extensions: []string{"mxl"},
	},
	"application/vnd.recordare.musicxml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"musicxml"},
	},
	"application/vnd.rig.cryptonote": &Spec{
		Source:     "iana",
		Extensions: []string{"cryptonote"},
	},
	"application/vnd.rim.cod": &Spec{
		Source:     "apache",
		Extensions: []string{"cod"},
	},
	"application/vnd.rn-realmedia": &Spec{
		Source:     "apache",
		Extensions: []string{"rm"},
	},
	"application/vnd.rn-realmedia-vbr": &Spec{
		Source:     "apache",
		Extensions: []string{"rmvb"},
	},
	"application/vnd.route66.link66+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"link66"},
	},
	"application/vnd.sailingtracker.track": &Spec{
		Source:     "iana",
		Extensions: []string{"st"},
	},
	"application/vnd.seemail": &Spec{
		Source:     "iana",
		Extensions: []string{"see"},
	},
	"application/vnd.sema": &Spec{
		Source:     "iana",
		Extensions: []string{"sema"},
	},
	"application/vnd.semd": &Spec{
		Source:     "iana",
		Extensions: []string{"semd"},
	},
	"application/vnd.semf": &Spec{
		Source:     "iana",
		Extensions: []string{"semf"},
	},
	"application/vnd.shana.informed.formdata": &Spec{
		Source:     "iana",
		Extensions: []string{"ifm"},
	},
	"application/vnd.shana.informed.formtemplate": &Spec{
		Source:     "iana",
		Extensions: []string{"itp"},
	},
	"application/vnd.shana.informed.interchange": &Spec{
		Source:     "iana",
		Extensions: []string{"iif"},
	},
	"application/vnd.shana.informed.package": &Spec{
		Source:     "iana",
		Extensions: []string{"ipk"},
	},
	"application/vnd.simtech-mindmapper": &Spec{
		Source:     "iana",
		Extensions: []string{"twd", "twds"},
	},
	"application/vnd.smaf": &Spec{
		Source:     "iana",
		Extensions: []string{"mmf"},
	},
	"application/vnd.smart.teacher": &Spec{
		Source:     "iana",
		Extensions: []string{"teacher"},
	},
	"application/vnd.software602.filler.form+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"fo"},
	},
	"application/vnd.solent.sdkm+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"sdkm", "sdkd"},
	},
	"application/vnd.spotfire.dxp": &Spec{
		Source:     "iana",
		Extensions: []string{"dxp"},
	},
	"application/vnd.spotfire.sfs": &Spec{
		Source:     "iana",
		Extensions: []string{"sfs"},
	},
	"application/vnd.stardivision.calc": &Spec{
		Source:     "apache",
		Extensions: []string{"sdc"},
	},
	"application/vnd.stardivision.draw": &Spec{
		Source:     "apache",
		Extensions: []string{"sda"},
	},
	"application/vnd.stardivision.impress": &Spec{
		Source:     "apache",
		Extensions: []string{"sdd"},
	},
	"application/vnd.stardivision.math": &Spec{
		Source:     "apache",
		Extensions: []string{"smf"},
	},
	"application/vnd.stardivision.writer": &Spec{
		Source:     "apache",
		Extensions: []string{"sdw", "vor"},
	},
	"application/vnd.stardivision.writer-global": &Spec{
		Source:     "apache",
		Extensions: []string{"sgl"},
	},
	"application/vnd.stepmania.package": &Spec{
		Source:     "iana",
		Extensions: []string{"smzip"},
	},
	"application/vnd.stepmania.stepchart": &Spec{
		Source:     "iana",
		Extensions: []string{"sm"},
	},
	"application/vnd.sun.wadl+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"wadl"},
	},
	"application/vnd.sun.xml.calc": &Spec{
		Source:     "apache",
		Extensions: []string{"sxc"},
	},
	"application/vnd.sun.xml.calc.template": &Spec{
		Source:     "apache",
		Extensions: []string{"stc"},
	},
	"application/vnd.sun.xml.draw": &Spec{
		Source:     "apache",
		Extensions: []string{"sxd"},
	},
	"application/vnd.sun.xml.draw.template": &Spec{
		Source:     "apache",
		Extensions: []string{"std"},
	},
	"application/vnd.sun.xml.impress": &Spec{
		Source:     "apache",
		Extensions: []string{"sxi"},
	},
	"application/vnd.sun.xml.impress.template": &Spec{
		Source:     "apache",
		Extensions: []string{"sti"},
	},
	"application/vnd.sun.xml.math": &Spec{
		Source:     "apache",
		Extensions: []string{"sxm"},
	},
	"application/vnd.sun.xml.writer": &Spec{
		Source:     "apache",
		Extensions: []string{"sxw"},
	},
	"application/vnd.sun.xml.writer.global": &Spec{
		Source:     "apache",
		Extensions: []string{"sxg"},
	},
	"application/vnd.sun.xml.writer.template": &Spec{
		Source:     "apache",
		Extensions: []string{"stw"},
	},
	"application/vnd.sus-calendar": &Spec{
		Source:     "iana",
		Extensions: []string{"sus", "susp"},
	},
	"application/vnd.svd": &Spec{
		Source:     "iana",
		Extensions: []string{"svd"},
	},
	"application/vnd.symbian.install": &Spec{
		Source:     "apache",
		Extensions: []string{"sis", "sisx"},
	},
	"application/vnd.syncml+xml": &Spec{
		Source:       "iana",
		CharEncoding: "UTF-8",
		Compressible: &trueVal,
		Extensions:   []string{"xsm"},
	},
	"application/vnd.syncml.dm+wbxml": &Spec{
		Source:       "iana",
		CharEncoding: "UTF-8",
		Extensions:   []string{"bdm"},
	},
	"application/vnd.syncml.dm+xml": &Spec{
		Source:       "iana",
		CharEncoding: "UTF-8",
		Compressible: &trueVal,
		Extensions:   []string{"xdm"},
	},
	"application/vnd.syncml.dmddf+xml": &Spec{
		Source:       "iana",
		CharEncoding: "UTF-8",
		Compressible: &trueVal,
		Extensions:   []string{"ddf"},
	},
	"application/vnd.tao.intent-module-archive": &Spec{
		Source:     "iana",
		Extensions: []string{"tao"},
	},
	"application/vnd.tcpdump.pcap": &Spec{
		Source:     "iana",
		Extensions: []string{"pcap", "cap", "dmp"},
	},
	"application/vnd.tmobile-livetv": &Spec{
		Source:     "iana",
		Extensions: []string{"tmo"},
	},
	"application/vnd.trid.tpt": &Spec{
		Source:     "iana",
		Extensions: []string{"tpt"},
	},
	"application/vnd.triscape.mxs": &Spec{
		Source:     "iana",
		Extensions: []string{"mxs"},
	},
	"application/vnd.trueapp": &Spec{
		Source:     "iana",
		Extensions: []string{"tra"},
	},
	"application/vnd.ufdl": &Spec{
		Source:     "iana",
		Extensions: []string{"ufd", "ufdl"},
	},
	"application/vnd.uiq.theme": &Spec{
		Source:     "iana",
		Extensions: []string{"utz"},
	},
	"application/vnd.umajin": &Spec{
		Source:     "iana",
		Extensions: []string{"umj"},
	},
	"application/vnd.unity": &Spec{
		Source:     "iana",
		Extensions: []string{"unityweb"},
	},
	"application/vnd.uoml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"uoml"},
	},
	"application/vnd.vcx": &Spec{
		Source:     "iana",
		Extensions: []string{"vcx"},
	},
	"application/vnd.visio": &Spec{
		Source:     "iana",
		Extensions: []string{"vsd", "vst", "vss", "vsw"},
	},
	"application/vnd.visionary": &Spec{
		Source:     "iana",
		Extensions: []string{"vis"},
	},
	"application/vnd.vsf": &Spec{
		Source:     "iana",
		Extensions: []string{"vsf"},
	},
	"application/vnd.wap.wbxml": &Spec{
		Source:       "iana",
		CharEncoding: "UTF-8",
		Extensions:   []string{"wbxml"},
	},
	"application/vnd.wap.wmlc": &Spec{
		Source:     "iana",
		Extensions: []string{"wmlc"},
	},
	"application/vnd.wap.wmlscriptc": &Spec{
		Source:     "iana",
		Extensions: []string{"wmlsc"},
	},
	"application/vnd.webturbo": &Spec{
		Source:     "iana",
		Extensions: []string{"wtb"},
	},
	"application/vnd.wolfram.player": &Spec{
		Source:     "iana",
		Extensions: []string{"nbp"},
	},
	"application/vnd.wordperfect": &Spec{
		Source:     "iana",
		Extensions: []string{"wpd"},
	},
	"application/vnd.wqd": &Spec{
		Source:     "iana",
		Extensions: []string{"wqd"},
	},
	"application/vnd.wt.stf": &Spec{
		Source:     "iana",
		Extensions: []string{"stf"},
	},
	"application/vnd.xara": &Spec{
		Source:     "iana",
		Extensions: []string{"xar"},
	},
	"application/vnd.xfdl": &Spec{
		Source:     "iana",
		Extensions: []string{"xfdl"},
	},
	"application/vnd.yamaha.hv-dic": &Spec{
		Source:     "iana",
		Extensions: []string{"hvd"},
	},
	"application/vnd.yamaha.hv-script": &Spec{
		Source:     "iana",
		Extensions: []string{"hvs"},
	},
	"application/vnd.yamaha.hv-voice": &Spec{
		Source:     "iana",
		Extensions: []string{"hvp"},
	},
	"application/vnd.yamaha.openscoreformat": &Spec{
		Source:     "iana",
		Extensions: []string{"osf"},
	},
	"application/vnd.yamaha.openscoreformat.osfpvg+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"osfpvg"},
	},
	"application/vnd.yamaha.smaf-audio": &Spec{
		Source:     "iana",
		Extensions: []string{"saf"},
	},
	"application/vnd.yamaha.smaf-phrase": &Spec{
		Source:     "iana",
		Extensions: []string{"spf"},
	},
	"application/vnd.yellowriver-custom-menu": &Spec{
		Source:     "iana",
		Extensions: []string{"cmp"},
	},
	"application/vnd.zul": &Spec{
		Source:     "iana",
		Extensions: []string{"zir", "zirz"},
	},
	"application/vnd.zzazz.deck+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"zaz"},
	},
	"application/voicexml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"vxml"},
	},
	"application/wasm": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"wasm"},
	},
	"application/widget": &Spec{
		Source:     "iana",
		Extensions: []string{"wgt"},
	},
	"application/winhlp": &Spec{
		Source:     "apache",
		Extensions: []string{"hlp"},
	},
	"application/wsdl+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"wsdl"},
	},
	"application/wspolicy+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"wspolicy"},
	},
	"application/x-7z-compressed": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"7z"},
	},
	"application/x-abiword": &Spec{
		Source:     "apache",
		Extensions: []string{"abw"},
	},
	"application/x-ace-compressed": &Spec{
		Source:     "apache",
		Extensions: []string{"ace"},
	},
	"application/x-apple-diskimage": &Spec{
		Source:     "apache",
		Extensions: []string{"dmg"},
	},
	"application/x-arj": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"arj"},
	},
	"application/x-authorware-bin": &Spec{
		Source:     "apache",
		Extensions: []string{"aab", "x32", "u32", "vox"},
	},
	"application/x-authorware-map": &Spec{
		Source:     "apache",
		Extensions: []string{"aam"},
	},
	"application/x-authorware-seg": &Spec{
		Source:     "apache",
		Extensions: []string{"aas"},
	},
	"application/x-bcpio": &Spec{
		Source:     "apache",
		Extensions: []string{"bcpio"},
	},
	"application/x-bdoc": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"bdoc"},
	},
	"application/x-bittorrent": &Spec{
		Source:     "apache",
		Extensions: []string{"torrent"},
	},
	"application/x-blorb": &Spec{
		Source:     "apache",
		Extensions: []string{"blb", "blorb"},
	},
	"application/x-bzip": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"bz"},
	},
	"application/x-bzip2": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"bz2", "boz"},
	},
	"application/x-cbr": &Spec{
		Source:     "apache",
		Extensions: []string{"cbr", "cba", "cbt", "cbz", "cb7"},
	},
	"application/x-cdlink": &Spec{
		Source:     "apache",
		Extensions: []string{"vcd"},
	},
	"application/x-cfs-compressed": &Spec{
		Source:     "apache",
		Extensions: []string{"cfs"},
	},
	"application/x-chat": &Spec{
		Source:     "apache",
		Extensions: []string{"chat"},
	},
	"application/x-chess-pgn": &Spec{
		Source:     "apache",
		Extensions: []string{"pgn"},
	},
	"application/x-chrome-extension": &Spec{
		Extensions: []string{"crx"},
	},
	"application/x-cocoa": &Spec{
		Source:     "nginx",
		Extensions: []string{"cco"},
	},
	"application/x-conference": &Spec{
		Source:     "apache",
		Extensions: []string{"nsc"},
	},
	"application/x-cpio": &Spec{
		Source:     "apache",
		Extensions: []string{"cpio"},
	},
	"application/x-csh": &Spec{
		Source:     "apache",
		Extensions: []string{"csh"},
	},
	"application/x-debian-package": &Spec{
		Source:     "apache",
		Extensions: []string{"deb", "udeb"},
	},
	"application/x-dgc-compressed": &Spec{
		Source:     "apache",
		Extensions: []string{"dgc"},
	},
	"application/x-director": &Spec{
		Source:     "apache",
		Extensions: []string{"dir", "dcr", "dxr", "cst", "cct", "cxt", "w3d", "fgd", "swa"},
	},
	"application/x-doom": &Spec{
		Source:     "apache",
		Extensions: []string{"wad"},
	},
	"application/x-dtbncx+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"ncx"},
	},
	"application/x-dtbook+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"dtb"},
	},
	"application/x-dtbresource+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"res"},
	},
	"application/x-dvi": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"dvi"},
	},
	"application/x-envoy": &Spec{
		Source:     "apache",
		Extensions: []string{"evy"},
	},
	"application/x-eva": &Spec{
		Source:     "apache",
		Extensions: []string{"eva"},
	},
	"application/x-font-bdf": &Spec{
		Source:     "apache",
		Extensions: []string{"bdf"},
	},
	"application/x-font-ghostscript": &Spec{
		Source:     "apache",
		Extensions: []string{"gsf"},
	},
	"application/x-font-linux-psf": &Spec{
		Source:     "apache",
		Extensions: []string{"psf"},
	},
	"application/x-font-pcf": &Spec{
		Source:     "apache",
		Extensions: []string{"pcf"},
	},
	"application/x-font-snf": &Spec{
		Source:     "apache",
		Extensions: []string{"snf"},
	},
	"application/x-font-type1": &Spec{
		Source:     "apache",
		Extensions: []string{"pfa", "pfb", "pfm", "afm"},
	},
	"application/x-freearc": &Spec{
		Source:     "apache",
		Extensions: []string{"arc"},
	},
	"application/x-futuresplash": &Spec{
		Source:     "apache",
		Extensions: []string{"spl"},
	},
	"application/x-gca-compressed": &Spec{
		Source:     "apache",
		Extensions: []string{"gca"},
	},
	"application/x-glulx": &Spec{
		Source:     "apache",
		Extensions: []string{"ulx"},
	},
	"application/x-gnumeric": &Spec{
		Source:     "apache",
		Extensions: []string{"gnumeric"},
	},
	"application/x-gramps-xml": &Spec{
		Source:     "apache",
		Extensions: []string{"gramps"},
	},
	"application/x-gtar": &Spec{
		Source:     "apache",
		Extensions: []string{"gtar"},
	},
	"application/x-hdf": &Spec{
		Source:     "apache",
		Extensions: []string{"hdf"},
	},
	"application/x-httpd-php": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"php"},
	},
	"application/x-install-instructions": &Spec{
		Source:     "apache",
		Extensions: []string{"install"},
	},
	"application/x-iso9660-image": &Spec{
		Source:     "apache",
		Extensions: []string{"iso"},
	},
	"application/x-iwork-keynote-sffkey": &Spec{
		Extensions: []string{"key"},
	},
	"application/x-iwork-numbers-sffnumbers": &Spec{
		Extensions: []string{"numbers"},
	},
	"application/x-iwork-pages-sffpages": &Spec{
		Extensions: []string{"pages"},
	},
	"application/x-java-archive-diff": &Spec{
		Source:     "nginx",
		Extensions: []string{"jardiff"},
	},
	"application/x-java-jnlp-file": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"jnlp"},
	},
	"application/x-keepass2": &Spec{
		Extensions: []string{"kdbx"},
	},
	"application/x-latex": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"latex"},
	},
	"application/x-lua-bytecode": &Spec{
		Extensions: []string{"luac"},
	},
	"application/x-lzh-compressed": &Spec{
		Source:     "apache",
		Extensions: []string{"lzh", "lha"},
	},
	"application/x-makeself": &Spec{
		Source:     "nginx",
		Extensions: []string{"run"},
	},
	"application/x-mie": &Spec{
		Source:     "apache",
		Extensions: []string{"mie"},
	},
	"application/x-mobipocket-ebook": &Spec{
		Source:     "apache",
		Extensions: []string{"prc", "mobi"},
	},
	"application/x-ms-application": &Spec{
		Source:     "apache",
		Extensions: []string{"application"},
	},
	"application/x-ms-shortcut": &Spec{
		Source:     "apache",
		Extensions: []string{"lnk"},
	},
	"application/x-ms-wmd": &Spec{
		Source:     "apache",
		Extensions: []string{"wmd"},
	},
	"application/x-ms-wmz": &Spec{
		Source:     "apache",
		Extensions: []string{"wmz"},
	},
	"application/x-ms-xbap": &Spec{
		Source:     "apache",
		Extensions: []string{"xbap"},
	},
	"application/x-msaccess": &Spec{
		Source:     "apache",
		Extensions: []string{"mdb"},
	},
	"application/x-msbinder": &Spec{
		Source:     "apache",
		Extensions: []string{"obd"},
	},
	"application/x-mscardfile": &Spec{
		Source:     "apache",
		Extensions: []string{"crd"},
	},
	"application/x-msclip": &Spec{
		Source:     "apache",
		Extensions: []string{"clp"},
	},
	"application/x-msdos-program": &Spec{
		Extensions: []string{"exe"},
	},
	"application/x-msdownload": &Spec{
		Source:     "apache",
		Extensions: []string{"exe", "dll", "com", "bat", "msi"},
	},
	"application/x-msmediaview": &Spec{
		Source:     "apache",
		Extensions: []string{"mvb", "m13", "m14"},
	},
	"application/x-msmetafile": &Spec{
		Source:     "apache",
		Extensions: []string{"wmf", "wmz", "emf", "emz"},
	},
	"application/x-msmoney": &Spec{
		Source:     "apache",
		Extensions: []string{"mny"},
	},
	"application/x-mspublisher": &Spec{
		Source:     "apache",
		Extensions: []string{"pub"},
	},
	"application/x-msschedule": &Spec{
		Source:     "apache",
		Extensions: []string{"scd"},
	},
	"application/x-msterminal": &Spec{
		Source:     "apache",
		Extensions: []string{"trm"},
	},
	"application/x-mswrite": &Spec{
		Source:     "apache",
		Extensions: []string{"wri"},
	},
	"application/x-netcdf": &Spec{
		Source:     "apache",
		Extensions: []string{"nc", "cdf"},
	},
	"application/x-ns-proxy-autoconfig": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"pac"},
	},
	"application/x-nzb": &Spec{
		Source:     "apache",
		Extensions: []string{"nzb"},
	},
	"application/x-perl": &Spec{
		Source:     "nginx",
		Extensions: []string{"pl", "pm"},
	},
	"application/x-pilot": &Spec{
		Source:     "nginx",
		Extensions: []string{"prc", "pdb"},
	},
	"application/x-pkcs12": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"p12", "pfx"},
	},
	"application/x-pkcs7-certificates": &Spec{
		Source:     "apache",
		Extensions: []string{"p7b", "spc"},
	},
	"application/x-pkcs7-certreqresp": &Spec{
		Source:     "apache",
		Extensions: []string{"p7r"},
	},
	"application/x-rar-compressed": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"rar"},
	},
	"application/x-redhat-package-manager": &Spec{
		Source:     "nginx",
		Extensions: []string{"rpm"},
	},
	"application/x-research-info-systems": &Spec{
		Source:     "apache",
		Extensions: []string{"ris"},
	},
	"application/x-sea": &Spec{
		Source:     "nginx",
		Extensions: []string{"sea"},
	},
	"application/x-sh": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"sh"},
	},
	"application/x-shar": &Spec{
		Source:     "apache",
		Extensions: []string{"shar"},
	},
	"application/x-shockwave-flash": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"swf"},
	},
	"application/x-silverlight-app": &Spec{
		Source:     "apache",
		Extensions: []string{"xap"},
	},
	"application/x-sql": &Spec{
		Source:     "apache",
		Extensions: []string{"sql"},
	},
	"application/x-stuffit": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"sit"},
	},
	"application/x-stuffitx": &Spec{
		Source:     "apache",
		Extensions: []string{"sitx"},
	},
	"application/x-subrip": &Spec{
		Source:     "apache",
		Extensions: []string{"srt"},
	},
	"application/x-sv4cpio": &Spec{
		Source:     "apache",
		Extensions: []string{"sv4cpio"},
	},
	"application/x-sv4crc": &Spec{
		Source:     "apache",
		Extensions: []string{"sv4crc"},
	},
	"application/x-t3vm-image": &Spec{
		Source:     "apache",
		Extensions: []string{"t3"},
	},
	"application/x-tads": &Spec{
		Source:     "apache",
		Extensions: []string{"gam"},
	},
	"application/x-tar": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"tar"},
	},
	"application/x-tcl": &Spec{
		Source:     "apache",
		Extensions: []string{"tcl", "tk"},
	},
	"application/x-tex": &Spec{
		Source:     "apache",
		Extensions: []string{"tex"},
	},
	"application/x-tex-tfm": &Spec{
		Source:     "apache",
		Extensions: []string{"tfm"},
	},
	"application/x-texinfo": &Spec{
		Source:     "apache",
		Extensions: []string{"texinfo", "texi"},
	},
	"application/x-tgif": &Spec{
		Source:     "apache",
		Extensions: []string{"obj"},
	},
	"application/x-ustar": &Spec{
		Source:     "apache",
		Extensions: []string{"ustar"},
	},
	"application/x-virtualbox-hdd": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"hdd"},
	},
	"application/x-virtualbox-ova": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"ova"},
	},
	"application/x-virtualbox-ovf": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"ovf"},
	},
	"application/x-virtualbox-vbox": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"vbox"},
	},
	"application/x-virtualbox-vbox-extpack": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"vbox-extpack"},
	},
	"application/x-virtualbox-vdi": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"vdi"},
	},
	"application/x-virtualbox-vhd": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"vhd"},
	},
	"application/x-virtualbox-vmdk": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"vmdk"},
	},
	"application/x-wais-source": &Spec{
		Source:     "apache",
		Extensions: []string{"src"},
	},
	"application/x-web-app-manifest+json": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"webapp"},
	},
	"application/x-x509-ca-cert": &Spec{
		Source:     "iana",
		Extensions: []string{"der", "crt", "pem"},
	},
	"application/x-xfig": &Spec{
		Source:     "apache",
		Extensions: []string{"fig"},
	},
	"application/x-xliff+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"xlf"},
	},
	"application/x-xpinstall": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"xpi"},
	},
	"application/x-xz": &Spec{
		Source:     "apache",
		Extensions: []string{"xz"},
	},
	"application/x-zmachine": &Spec{
		Source:     "apache",
		Extensions: []string{"z1", "z2", "z3", "z4", "z5", "z6", "z7", "z8"},
	},
	"application/xaml+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"xaml"},
	},
	"application/xcap-att+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xav"},
	},
	"application/xcap-caps+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xca"},
	},
	"application/xcap-diff+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xdf"},
	},
	"application/xcap-el+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xel"},
	},
	"application/xcap-ns+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xns"},
	},
	"application/xenc+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xenc"},
	},
	"application/xhtml+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xhtml", "xht"},
	},
	"application/xliff+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xlf"},
	},
	"application/xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xml", "xsl", "xsd", "rng"},
	},
	"application/xml-dtd": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"dtd"},
	},
	"application/xop+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xop"},
	},
	"application/xproc+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"xpl"},
	},
	"application/xslt+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xsl", "xslt"},
	},
	"application/xspf+xml": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"xspf"},
	},
	"application/xv+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"mxml", "xhvml", "xvml", "xvm"},
	},
	"application/yang": &Spec{
		Source:     "iana",
		Extensions: []string{"yang"},
	},
	"application/yin+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"yin"},
	},
	"application/zip": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"zip"},
	},
	"audio/3gpp": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"3gpp"},
	},
	"audio/adpcm": &Spec{
		Source:     "apache",
		Extensions: []string{"adp"},
	},
	"audio/amr": &Spec{
		Source:     "iana",
		Extensions: []string{"amr"},
	},
	"audio/basic": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"au", "snd"},
	},
	"audio/midi": &Spec{
		Source:     "apache",
		Extensions: []string{"mid", "midi", "kar", "rmi"},
	},
	"audio/mobile-xmf": &Spec{
		Source:     "iana",
		Extensions: []string{"mxmf"},
	},
	"audio/mp3": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"mp3"},
	},
	"audio/mp4": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"m4a", "mp4a"},
	},
	"audio/mpeg": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"mpga", "mp2", "mp2a", "mp3", "m2a", "m3a"},
	},
	"audio/ogg": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"oga", "ogg", "spx", "opus"},
	},
	"audio/s3m": &Spec{
		Source:     "apache",
		Extensions: []string{"s3m"},
	},
	"audio/silk": &Spec{
		Source:     "apache",
		Extensions: []string{"sil"},
	},
	"audio/vnd.dece.audio": &Spec{
		Source:     "iana",
		Extensions: []string{"uva", "uvva"},
	},
	"audio/vnd.digital-winds": &Spec{
		Source:     "iana",
		Extensions: []string{"eol"},
	},
	"audio/vnd.dra": &Spec{
		Source:     "iana",
		Extensions: []string{"dra"},
	},
	"audio/vnd.dts": &Spec{
		Source:     "iana",
		Extensions: []string{"dts"},
	},
	"audio/vnd.dts.hd": &Spec{
		Source:     "iana",
		Extensions: []string{"dtshd"},
	},
	"audio/vnd.lucent.voice": &Spec{
		Source:     "iana",
		Extensions: []string{"lvp"},
	},
	"audio/vnd.ms-playready.media.pya": &Spec{
		Source:     "iana",
		Extensions: []string{"pya"},
	},
	"audio/vnd.nuera.ecelp4800": &Spec{
		Source:     "iana",
		Extensions: []string{"ecelp4800"},
	},
	"audio/vnd.nuera.ecelp7470": &Spec{
		Source:     "iana",
		Extensions: []string{"ecelp7470"},
	},
	"audio/vnd.nuera.ecelp9600": &Spec{
		Source:     "iana",
		Extensions: []string{"ecelp9600"},
	},
	"audio/vnd.rip": &Spec{
		Source:     "iana",
		Extensions: []string{"rip"},
	},
	"audio/wav": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"wav"},
	},
	"audio/wave": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"wav"},
	},
	"audio/webm": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"weba"},
	},
	"audio/x-aac": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"aac"},
	},
	"audio/x-aiff": &Spec{
		Source:     "apache",
		Extensions: []string{"aif", "aiff", "aifc"},
	},
	"audio/x-caf": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"caf"},
	},
	"audio/x-flac": &Spec{
		Source:     "apache",
		Extensions: []string{"flac"},
	},
	"audio/x-m4a": &Spec{
		Source:     "nginx",
		Extensions: []string{"m4a"},
	},
	"audio/x-matroska": &Spec{
		Source:     "apache",
		Extensions: []string{"mka"},
	},
	"audio/x-mpegurl": &Spec{
		Source:     "apache",
		Extensions: []string{"m3u"},
	},
	"audio/x-ms-wax": &Spec{
		Source:     "apache",
		Extensions: []string{"wax"},
	},
	"audio/x-ms-wma": &Spec{
		Source:     "apache",
		Extensions: []string{"wma"},
	},
	"audio/x-pn-realaudio": &Spec{
		Source:     "apache",
		Extensions: []string{"ram", "ra"},
	},
	"audio/x-pn-realaudio-plugin": &Spec{
		Source:     "apache",
		Extensions: []string{"rmp"},
	},
	"audio/x-realaudio": &Spec{
		Source:     "nginx",
		Extensions: []string{"ra"},
	},
	"audio/x-wav": &Spec{
		Source:     "apache",
		Extensions: []string{"wav"},
	},
	"audio/xm": &Spec{
		Source:     "apache",
		Extensions: []string{"xm"},
	},
	"chemical/x-cdx": &Spec{
		Source:     "apache",
		Extensions: []string{"cdx"},
	},
	"chemical/x-cif": &Spec{
		Source:     "apache",
		Extensions: []string{"cif"},
	},
	"chemical/x-cmdf": &Spec{
		Source:     "apache",
		Extensions: []string{"cmdf"},
	},
	"chemical/x-cml": &Spec{
		Source:     "apache",
		Extensions: []string{"cml"},
	},
	"chemical/x-csml": &Spec{
		Source:     "apache",
		Extensions: []string{"csml"},
	},
	"chemical/x-xyz": &Spec{
		Source:     "apache",
		Extensions: []string{"xyz"},
	},
	"font/collection": &Spec{
		Source:     "iana",
		Extensions: []string{"ttc"},
	},
	"font/otf": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"otf"},
	},
	"font/ttf": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"ttf"},
	},
	"font/woff": &Spec{
		Source:     "iana",
		Extensions: []string{"woff"},
	},
	"font/woff2": &Spec{
		Source:     "iana",
		Extensions: []string{"woff2"},
	},
	"image/aces": &Spec{
		Source:     "iana",
		Extensions: []string{"exr"},
	},
	"image/apng": &Spec{
		Compressible: &falseVal,
		Extensions:   []string{"apng"},
	},
	"image/avif": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"avif"},
	},
	"image/bmp": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"bmp"},
	},
	"image/cgm": &Spec{
		Source:     "iana",
		Extensions: []string{"cgm"},
	},
	"image/dicom-rle": &Spec{
		Source:     "iana",
		Extensions: []string{"drle"},
	},
	"image/emf": &Spec{
		Source:     "iana",
		Extensions: []string{"emf"},
	},
	"image/fits": &Spec{
		Source:     "iana",
		Extensions: []string{"fits"},
	},
	"image/g3fax": &Spec{
		Source:     "iana",
		Extensions: []string{"g3"},
	},
	"image/gif": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"gif"},
	},
	"image/heic": &Spec{
		Source:     "iana",
		Extensions: []string{"heic"},
	},
	"image/heic-sequence": &Spec{
		Source:     "iana",
		Extensions: []string{"heics"},
	},
	"image/heif": &Spec{
		Source:     "iana",
		Extensions: []string{"heif"},
	},
	"image/heif-sequence": &Spec{
		Source:     "iana",
		Extensions: []string{"heifs"},
	},
	"image/hej2k": &Spec{
		Source:     "iana",
		Extensions: []string{"hej2"},
	},
	"image/hsj2": &Spec{
		Source:     "iana",
		Extensions: []string{"hsj2"},
	},
	"image/ief": &Spec{
		Source:     "iana",
		Extensions: []string{"ief"},
	},
	"image/jls": &Spec{
		Source:     "iana",
		Extensions: []string{"jls"},
	},
	"image/jp2": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"jp2", "jpg2"},
	},
	"image/jpeg": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"jpeg", "jpg", "jpe"},
	},
	"image/jph": &Spec{
		Source:     "iana",
		Extensions: []string{"jph"},
	},
	"image/jphc": &Spec{
		Source:     "iana",
		Extensions: []string{"jhc"},
	},
	"image/jpm": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"jpm"},
	},
	"image/jpx": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"jpx", "jpf"},
	},
	"image/jxr": &Spec{
		Source:     "iana",
		Extensions: []string{"jxr"},
	},
	"image/jxra": &Spec{
		Source:     "iana",
		Extensions: []string{"jxra"},
	},
	"image/jxrs": &Spec{
		Source:     "iana",
		Extensions: []string{"jxrs"},
	},
	"image/jxs": &Spec{
		Source:     "iana",
		Extensions: []string{"jxs"},
	},
	"image/jxsc": &Spec{
		Source:     "iana",
		Extensions: []string{"jxsc"},
	},
	"image/jxsi": &Spec{
		Source:     "iana",
		Extensions: []string{"jxsi"},
	},
	"image/jxss": &Spec{
		Source:     "iana",
		Extensions: []string{"jxss"},
	},
	"image/ktx": &Spec{
		Source:     "iana",
		Extensions: []string{"ktx"},
	},
	"image/ktx2": &Spec{
		Source:     "iana",
		Extensions: []string{"ktx2"},
	},
	"image/png": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"png"},
	},
	"image/prs.btif": &Spec{
		Source:     "iana",
		Extensions: []string{"btif"},
	},
	"image/prs.pti": &Spec{
		Source:     "iana",
		Extensions: []string{"pti"},
	},
	"image/sgi": &Spec{
		Source:     "apache",
		Extensions: []string{"sgi"},
	},
	"image/svg+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"svg", "svgz"},
	},
	"image/t38": &Spec{
		Source:     "iana",
		Extensions: []string{"t38"},
	},
	"image/tiff": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"tif", "tiff"},
	},
	"image/tiff-fx": &Spec{
		Source:     "iana",
		Extensions: []string{"tfx"},
	},
	"image/vnd.adobe.photoshop": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"psd"},
	},
	"image/vnd.airzip.accelerator.azv": &Spec{
		Source:     "iana",
		Extensions: []string{"azv"},
	},
	"image/vnd.dece.graphic": &Spec{
		Source:     "iana",
		Extensions: []string{"uvi", "uvvi", "uvg", "uvvg"},
	},
	"image/vnd.djvu": &Spec{
		Source:     "iana",
		Extensions: []string{"djvu", "djv"},
	},
	"image/vnd.dvb.subtitle": &Spec{
		Source:     "iana",
		Extensions: []string{"sub"},
	},
	"image/vnd.dwg": &Spec{
		Source:     "iana",
		Extensions: []string{"dwg"},
	},
	"image/vnd.dxf": &Spec{
		Source:     "iana",
		Extensions: []string{"dxf"},
	},
	"image/vnd.fastbidsheet": &Spec{
		Source:     "iana",
		Extensions: []string{"fbs"},
	},
	"image/vnd.fpx": &Spec{
		Source:     "iana",
		Extensions: []string{"fpx"},
	},
	"image/vnd.fst": &Spec{
		Source:     "iana",
		Extensions: []string{"fst"},
	},
	"image/vnd.fujixerox.edmics-mmr": &Spec{
		Source:     "iana",
		Extensions: []string{"mmr"},
	},
	"image/vnd.fujixerox.edmics-rlc": &Spec{
		Source:     "iana",
		Extensions: []string{"rlc"},
	},
	"image/vnd.microsoft.icon": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"ico"},
	},
	"image/vnd.ms-dds": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"dds"},
	},
	"image/vnd.ms-modi": &Spec{
		Source:     "iana",
		Extensions: []string{"mdi"},
	},
	"image/vnd.ms-photo": &Spec{
		Source:     "apache",
		Extensions: []string{"wdp"},
	},
	"image/vnd.net-fpx": &Spec{
		Source:     "iana",
		Extensions: []string{"npx"},
	},
	"image/vnd.pco.b16": &Spec{
		Source:     "iana",
		Extensions: []string{"b16"},
	},
	"image/vnd.tencent.tap": &Spec{
		Source:     "iana",
		Extensions: []string{"tap"},
	},
	"image/vnd.valve.source.texture": &Spec{
		Source:     "iana",
		Extensions: []string{"vtf"},
	},
	"image/vnd.wap.wbmp": &Spec{
		Source:     "iana",
		Extensions: []string{"wbmp"},
	},
	"image/vnd.xiff": &Spec{
		Source:     "iana",
		Extensions: []string{"xif"},
	},
	"image/vnd.zbrush.pcx": &Spec{
		Source:     "iana",
		Extensions: []string{"pcx"},
	},
	"image/webp": &Spec{
		Source:     "apache",
		Extensions: []string{"webp"},
	},
	"image/wmf": &Spec{
		Source:     "iana",
		Extensions: []string{"wmf"},
	},
	"image/x-3ds": &Spec{
		Source:     "apache",
		Extensions: []string{"3ds"},
	},
	"image/x-cmu-raster": &Spec{
		Source:     "apache",
		Extensions: []string{"ras"},
	},
	"image/x-cmx": &Spec{
		Source:     "apache",
		Extensions: []string{"cmx"},
	},
	"image/x-freehand": &Spec{
		Source:     "apache",
		Extensions: []string{"fh", "fhc", "fh4", "fh5", "fh7"},
	},
	"image/x-icon": &Spec{
		Source:       "apache",
		Compressible: &trueVal,
		Extensions:   []string{"ico"},
	},
	"image/x-jng": &Spec{
		Source:     "nginx",
		Extensions: []string{"jng"},
	},
	"image/x-mrsid-image": &Spec{
		Source:     "apache",
		Extensions: []string{"sid"},
	},
	"image/x-ms-bmp": &Spec{
		Source:       "nginx",
		Compressible: &trueVal,
		Extensions:   []string{"bmp"},
	},
	"image/x-pcx": &Spec{
		Source:     "apache",
		Extensions: []string{"pcx"},
	},
	"image/x-pict": &Spec{
		Source:     "apache",
		Extensions: []string{"pic", "pct"},
	},
	"image/x-portable-anymap": &Spec{
		Source:     "apache",
		Extensions: []string{"pnm"},
	},
	"image/x-portable-bitmap": &Spec{
		Source:     "apache",
		Extensions: []string{"pbm"},
	},
	"image/x-portable-graymap": &Spec{
		Source:     "apache",
		Extensions: []string{"pgm"},
	},
	"image/x-portable-pixmap": &Spec{
		Source:     "apache",
		Extensions: []string{"ppm"},
	},
	"image/x-rgb": &Spec{
		Source:     "apache",
		Extensions: []string{"rgb"},
	},
	"image/x-tga": &Spec{
		Source:     "apache",
		Extensions: []string{"tga"},
	},
	"image/x-xbitmap": &Spec{
		Source:     "apache",
		Extensions: []string{"xbm"},
	},
	"image/x-xpixmap": &Spec{
		Source:     "apache",
		Extensions: []string{"xpm"},
	},
	"image/x-xwindowdump": &Spec{
		Source:     "apache",
		Extensions: []string{"xwd"},
	},
	"message/disposition-notification": &Spec{
		Source:     "iana",
		Extensions: []string{"disposition-notification"},
	},
	"message/global": &Spec{
		Source:     "iana",
		Extensions: []string{"u8msg"},
	},
	"message/global-delivery-status": &Spec{
		Source:     "iana",
		Extensions: []string{"u8dsn"},
	},
	"message/global-disposition-notification": &Spec{
		Source:     "iana",
		Extensions: []string{"u8mdn"},
	},
	"message/global-headers": &Spec{
		Source:     "iana",
		Extensions: []string{"u8hdr"},
	},
	"message/rfc822": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"eml", "mime"},
	},
	"message/vnd.wfa.wsc": &Spec{
		Source:     "iana",
		Extensions: []string{"wsc"},
	},
	"model/3mf": &Spec{
		Source:     "iana",
		Extensions: []string{"3mf"},
	},
	"model/gltf+json": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"gltf"},
	},
	"model/gltf-binary": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"glb"},
	},
	"model/iges": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"igs", "iges"},
	},
	"model/mesh": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"msh", "mesh", "silo"},
	},
	"model/mtl": &Spec{
		Source:     "iana",
		Extensions: []string{"mtl"},
	},
	"model/obj": &Spec{
		Source:     "iana",
		Extensions: []string{"obj"},
	},
	"model/step+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"stpx"},
	},
	"model/step+zip": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"stpz"},
	},
	"model/step-xml+zip": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"stpxz"},
	},
	"model/stl": &Spec{
		Source:     "iana",
		Extensions: []string{"stl"},
	},
	"model/vnd.collada+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"dae"},
	},
	"model/vnd.dwf": &Spec{
		Source:     "iana",
		Extensions: []string{"dwf"},
	},
	"model/vnd.gdl": &Spec{
		Source:     "iana",
		Extensions: []string{"gdl"},
	},
	"model/vnd.gtw": &Spec{
		Source:     "iana",
		Extensions: []string{"gtw"},
	},
	"model/vnd.mts": &Spec{
		Source:     "iana",
		Extensions: []string{"mts"},
	},
	"model/vnd.opengex": &Spec{
		Source:     "iana",
		Extensions: []string{"ogex"},
	},
	"model/vnd.parasolid.transmit.binary": &Spec{
		Source:     "iana",
		Extensions: []string{"x_b"},
	},
	"model/vnd.parasolid.transmit.text": &Spec{
		Source:     "iana",
		Extensions: []string{"x_t"},
	},
	"model/vnd.sap.vds": &Spec{
		Source:     "iana",
		Extensions: []string{"vds"},
	},
	"model/vnd.usdz+zip": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"usdz"},
	},
	"model/vnd.valve.source.compiled-map": &Spec{
		Source:     "iana",
		Extensions: []string{"bsp"},
	},
	"model/vnd.vtu": &Spec{
		Source:     "iana",
		Extensions: []string{"vtu"},
	},
	"model/vrml": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"wrl", "vrml"},
	},
	"model/x3d+binary": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"x3db", "x3dbz"},
	},
	"model/x3d+fastinfoset": &Spec{
		Source:     "iana",
		Extensions: []string{"x3db"},
	},
	"model/x3d+vrml": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"x3dv", "x3dvz"},
	},
	"model/x3d+xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"x3d", "x3dz"},
	},
	"model/x3d-vrml": &Spec{
		Source:     "iana",
		Extensions: []string{"x3dv"},
	},
	"text/cache-manifest": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"appcache", "manifest"},
	},
	"text/calendar": &Spec{
		Source:     "iana",
		Extensions: []string{"ics", "ifb"},
	},
	"text/coffeescript": &Spec{
		Extensions: []string{"coffee", "litcoffee"},
	},
	"text/css": &Spec{
		Source:       "iana",
		CharEncoding: "UTF-8",
		Compressible: &trueVal,
		Extensions:   []string{"css"},
	},
	"text/csv": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"csv"},
	},
	"text/html": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"html", "htm", "shtml"},
	},
	"text/jade": &Spec{
		Extensions: []string{"jade"},
	},
	"text/jsx": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"jsx"},
	},
	"text/less": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"less"},
	},
	"text/markdown": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"markdown", "md"},
	},
	"text/mathml": &Spec{
		Source:     "nginx",
		Extensions: []string{"mml"},
	},
	"text/mdx": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"mdx"},
	},
	"text/n3": &Spec{
		Source:       "iana",
		CharEncoding: "UTF-8",
		Compressible: &trueVal,
		Extensions:   []string{"n3"},
	},
	"text/plain": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"txt", "text", "conf", "def", "list", "log", "in", "ini"},
	},
	"text/prs.lines.tag": &Spec{
		Source:     "iana",
		Extensions: []string{"dsc"},
	},
	"text/richtext": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"rtx"},
	},
	"text/rtf": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"rtf"},
	},
	"text/sgml": &Spec{
		Source:     "iana",
		Extensions: []string{"sgml", "sgm"},
	},
	"text/shex": &Spec{
		Source:     "iana",
		Extensions: []string{"shex"},
	},
	"text/slim": &Spec{
		Extensions: []string{"slim", "slm"},
	},
	"text/spdx": &Spec{
		Source:     "iana",
		Extensions: []string{"spdx"},
	},
	"text/stylus": &Spec{
		Extensions: []string{"stylus", "styl"},
	},
	"text/tab-separated-values": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"tsv"},
	},
	"text/troff": &Spec{
		Source:     "iana",
		Extensions: []string{"t", "tr", "roff", "man", "me", "ms"},
	},
	"text/turtle": &Spec{
		Source:       "iana",
		CharEncoding: "UTF-8",
		Extensions:   []string{"ttl"},
	},
	"text/uri-list": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"uri", "uris", "urls"},
	},
	"text/vcard": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"vcard"},
	},
	"text/vnd.curl": &Spec{
		Source:     "iana",
		Extensions: []string{"curl"},
	},
	"text/vnd.curl.dcurl": &Spec{
		Source:     "apache",
		Extensions: []string{"dcurl"},
	},
	"text/vnd.curl.mcurl": &Spec{
		Source:     "apache",
		Extensions: []string{"mcurl"},
	},
	"text/vnd.curl.scurl": &Spec{
		Source:     "apache",
		Extensions: []string{"scurl"},
	},
	"text/vnd.dvb.subtitle": &Spec{
		Source:     "iana",
		Extensions: []string{"sub"},
	},
	"text/vnd.familysearch.gedcom": &Spec{
		Source:     "iana",
		Extensions: []string{"ged"},
	},
	"text/vnd.fly": &Spec{
		Source:     "iana",
		Extensions: []string{"fly"},
	},
	"text/vnd.fmi.flexstor": &Spec{
		Source:     "iana",
		Extensions: []string{"flx"},
	},
	"text/vnd.graphviz": &Spec{
		Source:     "iana",
		Extensions: []string{"gv"},
	},
	"text/vnd.in3d.3dml": &Spec{
		Source:     "iana",
		Extensions: []string{"3dml"},
	},
	"text/vnd.in3d.spot": &Spec{
		Source:     "iana",
		Extensions: []string{"spot"},
	},
	"text/vnd.sun.j2me.app-descriptor": &Spec{
		Source:       "iana",
		CharEncoding: "UTF-8",
		Extensions:   []string{"jad"},
	},
	"text/vnd.wap.wml": &Spec{
		Source:     "iana",
		Extensions: []string{"wml"},
	},
	"text/vnd.wap.wmlscript": &Spec{
		Source:     "iana",
		Extensions: []string{"wmls"},
	},
	"text/vtt": &Spec{
		Source:       "iana",
		CharEncoding: "UTF-8",
		Compressible: &trueVal,
		Extensions:   []string{"vtt"},
	},
	"text/x-asm": &Spec{
		Source:     "apache",
		Extensions: []string{"s", "asm"},
	},
	"text/x-c": &Spec{
		Source:     "apache",
		Extensions: []string{"c", "cc", "cxx", "cpp", "h", "hh", "dic"},
	},
	"text/x-component": &Spec{
		Source:     "nginx",
		Extensions: []string{"htc"},
	},
	"text/x-fortran": &Spec{
		Source:     "apache",
		Extensions: []string{"f", "for", "f77", "f90"},
	},
	"text/x-handlebars-template": &Spec{
		Extensions: []string{"hbs"},
	},
	"text/x-java-source": &Spec{
		Source:     "apache",
		Extensions: []string{"java"},
	},
	"text/x-lua": &Spec{
		Extensions: []string{"lua"},
	},
	"text/x-markdown": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"mkd"},
	},
	"text/x-nfo": &Spec{
		Source:     "apache",
		Extensions: []string{"nfo"},
	},
	"text/x-opml": &Spec{
		Source:     "apache",
		Extensions: []string{"opml"},
	},
	"text/x-org": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"org"},
	},
	"text/x-pascal": &Spec{
		Source:     "apache",
		Extensions: []string{"p", "pas"},
	},
	"text/x-processing": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"pde"},
	},
	"text/x-sass": &Spec{
		Extensions: []string{"sass"},
	},
	"text/x-scss": &Spec{
		Extensions: []string{"scss"},
	},
	"text/x-setext": &Spec{
		Source:     "apache",
		Extensions: []string{"etx"},
	},
	"text/x-sfv": &Spec{
		Source:     "apache",
		Extensions: []string{"sfv"},
	},
	"text/x-suse-ymp": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"ymp"},
	},
	"text/x-uuencode": &Spec{
		Source:     "apache",
		Extensions: []string{"uu"},
	},
	"text/x-vcalendar": &Spec{
		Source:     "apache",
		Extensions: []string{"vcs"},
	},
	"text/x-vcard": &Spec{
		Source:     "apache",
		Extensions: []string{"vcf"},
	},
	"text/xml": &Spec{
		Source:       "iana",
		Compressible: &trueVal,
		Extensions:   []string{"xml"},
	},
	"text/yaml": &Spec{
		Compressible: &trueVal,
		Extensions:   []string{"yaml", "yml"},
	},
	"video/3gpp": &Spec{
		Source:     "iana",
		Extensions: []string{"3gp", "3gpp"},
	},
	"video/3gpp2": &Spec{
		Source:     "iana",
		Extensions: []string{"3g2"},
	},
	"video/h261": &Spec{
		Source:     "iana",
		Extensions: []string{"h261"},
	},
	"video/h263": &Spec{
		Source:     "iana",
		Extensions: []string{"h263"},
	},
	"video/h264": &Spec{
		Source:     "iana",
		Extensions: []string{"h264"},
	},
	"video/iso.segment": &Spec{
		Source:     "iana",
		Extensions: []string{"m4s"},
	},
	"video/jpeg": &Spec{
		Source:     "iana",
		Extensions: []string{"jpgv"},
	},
	"video/jpm": &Spec{
		Source:     "apache",
		Extensions: []string{"jpm", "jpgm"},
	},
	"video/mj2": &Spec{
		Source:     "iana",
		Extensions: []string{"mj2", "mjp2"},
	},
	"video/mp2t": &Spec{
		Source:     "iana",
		Extensions: []string{"ts"},
	},
	"video/mp4": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"mp4", "mp4v", "mpg4"},
	},
	"video/mpeg": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"mpeg", "mpg", "mpe", "m1v", "m2v"},
	},
	"video/ogg": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"ogv"},
	},
	"video/quicktime": &Spec{
		Source:       "iana",
		Compressible: &falseVal,
		Extensions:   []string{"qt", "mov"},
	},
	"video/vnd.dece.hd": &Spec{
		Source:     "iana",
		Extensions: []string{"uvh", "uvvh"},
	},
	"video/vnd.dece.mobile": &Spec{
		Source:     "iana",
		Extensions: []string{"uvm", "uvvm"},
	},
	"video/vnd.dece.pd": &Spec{
		Source:     "iana",
		Extensions: []string{"uvp", "uvvp"},
	},
	"video/vnd.dece.sd": &Spec{
		Source:     "iana",
		Extensions: []string{"uvs", "uvvs"},
	},
	"video/vnd.dece.video": &Spec{
		Source:     "iana",
		Extensions: []string{"uvv", "uvvv"},
	},
	"video/vnd.dvb.file": &Spec{
		Source:     "iana",
		Extensions: []string{"dvb"},
	},
	"video/vnd.fvt": &Spec{
		Source:     "iana",
		Extensions: []string{"fvt"},
	},
	"video/vnd.mpegurl": &Spec{
		Source:     "iana",
		Extensions: []string{"mxu", "m4u"},
	},
	"video/vnd.ms-playready.media.pyv": &Spec{
		Source:     "iana",
		Extensions: []string{"pyv"},
	},
	"video/vnd.uvvu.mp4": &Spec{
		Source:     "iana",
		Extensions: []string{"uvu", "uvvu"},
	},
	"video/vnd.vivo": &Spec{
		Source:     "iana",
		Extensions: []string{"viv"},
	},
	"video/webm": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"webm"},
	},
	"video/x-f4v": &Spec{
		Source:     "apache",
		Extensions: []string{"f4v"},
	},
	"video/x-fli": &Spec{
		Source:     "apache",
		Extensions: []string{"fli"},
	},
	"video/x-flv": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"flv"},
	},
	"video/x-m4v": &Spec{
		Source:     "apache",
		Extensions: []string{"m4v"},
	},
	"video/x-matroska": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"mkv", "mk3d", "mks"},
	},
	"video/x-mng": &Spec{
		Source:     "apache",
		Extensions: []string{"mng"},
	},
	"video/x-ms-asf": &Spec{
		Source:     "apache",
		Extensions: []string{"asf", "asx"},
	},
	"video/x-ms-vob": &Spec{
		Source:     "apache",
		Extensions: []string{"vob"},
	},
	"video/x-ms-wm": &Spec{
		Source:     "apache",
		Extensions: []string{"wm"},
	},
	"video/x-ms-wmv": &Spec{
		Source:       "apache",
		Compressible: &falseVal,
		Extensions:   []string{"wmv"},
	},
	"video/x-ms-wmx": &Spec{
		Source:     "apache",
		Extensions: []string{"wmx"},
	},
	"video/x-ms-wvx": &Spec{
		Source:     "apache",
		Extensions: []string{"wvx"},
	},
	"video/x-msvideo": &Spec{
		Source:     "apache",
		Extensions: []string{"avi"},
	},
	"video/x-sgi-movie": &Spec{
		Source:     "apache",
		Extensions: []string{"movie"},
	},
	"video/x-smv": &Spec{
		Source:     "apache",
		Extensions: []string{"smv"},
	},
	"x-conference/x-cooltalk": &Spec{
		Source:     "apache",
		Extensions: []string{"ice"},
	},
}
